#!/usr/bin/env ruby

#
#  demofan  -- Test the Application class with commands
#

require "applfan"


class DemoFan < ApplicationFan

  NAME      = "demofan"
  VERSION   = "1.0"
  SUMMARY   = "Test the Application class with commands"
  COPYRIGHT = "(C) 2020 Bertram Scharpf"
  LICENSE   = "For internal use only"
  AUTHOR    = "Bertram Scharpf <software@bertram-scharpf.de>"

  DESCRIPTION = <<~EOT
    This is an example how to define an Application subclass
    with commands inside.
  EOT

  define_option "h", :help,                         "show this options list"
  alias_option  "h", "help"
  define_option "V", :version,                    "show version information"
  alias_option  "V", "version"


  class Init < Command
    NAME        = "init"
    SUMMARY     = "Initialize"
    DESCRIPTION = <<~EOT
      Initialization of nothing.
    EOT
    define_option "h", :help,                       "show init's options list"
    alias_option  "h", "help"
    def run
      puts "Initializing...done."
    end
  end

  class Run < Command
    NAME        = "run"
    SUMMARY     = "Run a job"
    DESCRIPTION = <<~EOT
      Running nothing.
    EOT
    define_option "h", :help,                        "show run's options list"
    alias_option  "h", "help"
    def run
      puts "Running...done."
    end
  end

  class Cleanup < Command
    NAME        = "cleanup"
    SUMMARY     = "Cleanup"
    DESCRIPTION = <<~EOT
      Cleanup of nothing.
    EOT
    define_option "h", :help,                    "show cleanup's options list"
    alias_option  "h", "help"
    def run
      puts "Cleaning up...done."
    end
  end

end


DemoFan.run

